spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_8faae819f4481eb?user=be301fdf3a1134&password=f7c59416
    username: be301fdf3a1134
    password: f7c59416
    dbcp:
      max-active: 4
    tomcat:
      max-active: 4
---
server:
  context-path: /
  max-http-header-size: 2012333
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-request-size: 10Mb
---
spring:
  datasource:
    url:
      jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_8faae819f4481eb?user=be301fdf3a1134&password=f7c59416
